xe20180605_002625

diff --git a/xe-ca-cert/etc/ca-certificates/update.d/xe-ca-mozilla-keystore b/xe-ca-cert/etc/ca-certificates/update.d/xe-ca-mozilla-keystore
--- a/xe-ca-cert/etc/ca-certificates/update.d/xe-ca-mozilla-keystore
+++ b/xe-ca-cert/etc/ca-certificates/update.d/xe-ca-mozilla-keystore
@@ -4,7 +4,7 @@ set -e
 
 FIRST_UID=1000
 LAST_UID=29999
-certificateFile="/etc/ssl/certs/Xunde_Energie_Intermediate-CA-Chain.pem"
+certificateFile="/etc/ssl/certs/Xunde_Energie_Chain-CA.pem"
 certificateNameDel="Xunde Energie Intermediate CA - Xunde Energie"
 certificateName="Xunde Energie Intermediate CA"
 
@@ -12,14 +12,19 @@ echo Delete old CA Certificates
 
 IFS=$'\n'
 awk -F : 'BEGIN{OFS=" "} $3 >= fuid && $3 <= luid {print $1,$6}' fuid=$FIRST_UID luid=$LAST_UID /etc/passwd | while IFS=" " read -r u h; do
-    for certDB in $(find -H "${h}"/.mozilla* "${h}"/.thunderbird* "${h}"/.icedove* -name "cert8.db" )
+    for certDB in $(find -H "${h}"/.mozilla* "${h}"/.thunderbird* "${h}"/.icedove* -name "cert8.db" 2>/dev/null )
     do
       echo delete cert from $certDB
       certDir="$(dirname ${certDB})";
       r=0
       while test $r -eq 0 ;do 
-          echo runuser -u $u -- certutil -d "${certDir}" -D -n "${certificateName}" ;
-          runuser -u $u -- certutil -d "${certDir}" -D -n "${certificateName}" || r=$?
+          echo runuser -u $u -- certutil -d "sql:${certDir}" -D -n "${certificateName}" ;
+          runuser -u $u -- certutil -d "sql:${certDir}" -D -n "${certificateName}" 2>/dev/null|| r=$?
+          echo return-value: $r
+      done
+      while test $r -eq 0 ;do 
+          echo runuser -u $u -- certutil -d "dbm:${certDir}" -D -n "${certificateName}" ;
+          runuser -u $u -- certutil -d "dbm:${certDir}" -D -n "${certificateName}" 2>/dev/null|| r=$?
           echo return-value: $r
       done
     done
@@ -28,11 +33,13 @@ done
 echo Install the new CA Certificate
 IFS=$'\n'
 awk -F : '$3 >= fuid && $3 <= luid {print $1,$6}' fuid=$FIRST_UID luid=$LAST_UID /etc/passwd | while IFS=" " read u h; do
-    for certDB in $(find -H "${h}"/.mozilla* "${h}"/.thunderbird* "${h}"/.icedove* -name "cert8.db" 2>/dev/null)
+    for certDB in $(find -H "${h}"/.mozilla* "${h}"/.thunderbird* "${h}"/.icedove* -name "cert8.db"  2>/dev/null)
     do
       echo $certDB
       certDir="$(dirname ${certDB})";
-      echo runuser -u $u -- certutil -A -n "${certificateName}" -t "TCu,Cuw,Tuw" -i "${certificateFile}" -d "${certDir}" || echo error is $?
-      runuser -u $u -- certutil -A -n "${certificateName}" -t "TCu,Cuw,Tuw" -i "${certificateFile}" -d "${certDir}" || echo error is $?
+      echo runuser -u $u -- certutil -A -n "${certificateName}" -t "TCu,Cuw,Tuw" -i "${certificateFile}" -d "dbm:${certDir}" || echo error is $?
+      echo runuser -u $u -- certutil -A -n "${certificateName}" -t "TCu,Cuw,Tuw" -i "${certificateFile}" -d "sql:${certDir}" || echo error is $?
+      runuser -u $u -- certutil -A -n "${certificateName}" -t "TCu,Cuw,Tuw" -i "${certificateFile}" -d "dbm:${certDir}" || echo error is $?
+      runuser -u $u -- certutil -A -n "${certificateName}" -t "TCu,Cuw,Tuw" -i "${certificateFile}" -d "sql:${certDir}" || echo error is $?
     done
 done
