xe20171108_141529

diff --git a/xe-ca-cert/etc/ca-certificates/update.d/xe-ca-mozilla-keystore b/xe-ca-cert/etc/ca-certificates/update.d/xe-ca-mozilla-keystore
--- a/xe-ca-cert/etc/ca-certificates/update.d/xe-ca-mozilla-keystore
+++ b/xe-ca-cert/etc/ca-certificates/update.d/xe-ca-mozilla-keystore
@@ -4,7 +4,7 @@ set -e
 
 FIRST_UID=1000
 LAST_UID=29999
-certificateFile="/etc/ssl/certs/xe-ca-chain.cert.pem"
+certificateFile="/etc/ssl/certs/Xunde_Energie_Intermediate-CA-Chain.pem"
 certificateNameDel="Xunde Energie Intermediate CA - Xunde Energie"
 certificateName="Xunde Energie Intermediate CA"
 
@@ -20,7 +20,7 @@ awk -F : 'BEGIN{OFS=" "} $3 >= fuid && $3 <= luid {print $1,$6}' fuid=$FIRST_UID
       while test $r -eq 0 ;do 
           echo runuser -u $u -- certutil -d "${certDir}" -D -n "${certificateName}" ;
           runuser -u $u -- certutil -d "${certDir}" -D -n "${certificateName}" || r=$?
-          echo r $r
+          echo return-value: $r
       done
     done
 done
@@ -32,6 +32,7 @@ awk -F : '$3 >= fuid && $3 <= luid {print $1,$6}' fuid=$FIRST_UID luid=$LAST_UID
     do
       echo $certDB
       certDir="$(dirname ${certDB})";
+      echo runuser -u $u -- certutil -A -n "${certificateName}" -t "TCu,Cuw,Tuw" -i "${certificateFile}" -d "${certDir}" || echo error is $?
       runuser -u $u -- certutil -A -n "${certificateName}" -t "TCu,Cuw,Tuw" -i "${certificateFile}" -d "${certDir}" || echo error is $?
     done
 done
